// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlYWsBOq0FaCeDpsCibNclqyvnc6K28j8',
    appId: '1:253511843396:web:3ba40a361275a7583ec611',
    messagingSenderId: '253511843396',
    projectId: 'thiran-tech',
    authDomain: 'thiran-tech.firebaseapp.com',
    storageBucket: 'thiran-tech.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKwEMDusxWPuuqg2b0KeTD0ErZSAW0j5s',
    appId: '1:253511843396:android:370ff282acdb53713ec611',
    messagingSenderId: '253511843396',
    projectId: 'thiran-tech',
    storageBucket: 'thiran-tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcQsI72ZtTMaB5OZjyK5t2Mi53NJwHK5U',
    appId: '1:253511843396:ios:b3cc4a8afce562c23ec611',
    messagingSenderId: '253511843396',
    projectId: 'thiran-tech',
    storageBucket: 'thiran-tech.appspot.com',
    iosBundleId: 'com.example.thiranTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcQsI72ZtTMaB5OZjyK5t2Mi53NJwHK5U',
    appId: '1:253511843396:ios:b3cc4a8afce562c23ec611',
    messagingSenderId: '253511843396',
    projectId: 'thiran-tech',
    storageBucket: 'thiran-tech.appspot.com',
    iosBundleId: 'com.example.thiranTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlYWsBOq0FaCeDpsCibNclqyvnc6K28j8',
    appId: '1:253511843396:web:554c5f2cb98591b53ec611',
    messagingSenderId: '253511843396',
    projectId: 'thiran-tech',
    authDomain: 'thiran-tech.firebaseapp.com',
    storageBucket: 'thiran-tech.appspot.com',
  );
}
